export class EquipoModel{
    constructor(
        public tipo?: string,
        public subtipo?: string,
        public subtipoFuncionEquipo?: string,
        public nomenclatura?:string,
        public marca?: string,
        public serial?: string,
        public tag?: string,
        public modelo?: string,
        public funcionamiento?: string,
        public tamano_dial?: string,
        public dimension_conexion?: string,
        public tipo_conexion?: string,
        public material_carcaza?: string,
        public unidades_rango?: string,
        public rango_min?: number,
        public rango_max?: number,
        public p_funcionamiento?: string,
        public tipo_elemento?: string,
        public indicador_auxiliar?: string,
        public req_especial?:string ,
        public alimentacion_electrica?:string ,
        public exactitud?:string ,
        public elemento_medicion?:string ,
        public comunicacion?:string ,
        public material_diafragma?:string ,
        public material_cuerpo?:string ,
        public tipo_manifold?:string ,
        public fabricante_manifold?:string ,
        public fecha_creacion?:string ,
        public usuario_creador?:string ,
        public usuario_modificador?:string ,
        public tercero?:string ,
        public estado?:string ,
        public ubicacion?:string,
        public _id?: string,
    ){}
}